expt_dir: "./expts/DeepLabV3"

dataset: 
  VegAnn_path: "/home/kaaviyavelumani/Documents/codes/personal/VegAnn/data/VegAnn_dataset"
  n_split: 5
  species: 
  system: "Handheld cameras" #(options: "Handeld cameras", "DHP","IOT", "UAV", "Phenomobile" or "Phone Camera")
  orientation: Nadir  # Orientation of the images (options: "Nadir", 45 or "DHP")
  alltvt: False


training:
  batch_size: 16
  max_epochs: 15
  log_every_n_steps: 15
  every_n_epochs: 2
  limit_train_batches: 1.
  limit_val_batches: 1.
  limit_test_batches: 1.
  precision: medium
  devices: 1
  accelerator: "cpu"
  num_workers: 8
  pin_memory: False


model:
  name: DeepLabV3
  encoder: resnet34 # resnet50
  pretrained: imagenet


WandB_config:
  sss: ccc
  xxc: xxx
  project: xxx
