expt_dir: "./expts/DeepLabV3"

# Parameter to 
dataset: 
  VegAnn_path: "/home/data/VegAnn_dataset" # specify directory of the dataset (lcoation of images and annotations folder with VegAnn_dataset.csv) 
  n_split: 1  # Specify the split use for Training Validation or Test (integer between 1 or 5)
  species: # Species to include in the dataset (example: ["Wheat","Maize"])
  system: # System used to acquire the images (options: "Handeld cameras", "DHP","IOT", "UAV", "Phenomobile" or "Phone Camera")
  orientation:  # Orientation of the images (options: "Nadir", 45 or "DHP")
  alltvt: False # Whether to use all images (Training/Validation/Test) for Training

# Training configuration 
training:
  batch_size: 16
  max_epochs: 15
  log_every_n_steps: 15
  every_n_epochs: 2
  limit_train_batches: 1.
  limit_val_batches: 1.
  limit_test_batches: 1.
  precision: medium
  devices: 1
  accelerator: "cpu"
  num_workers: 8
  pin_memory: False


model:
  name: DeepLabV3
  encoder: resnet34 # resnet50
  pretrained: imagenet


WandB_config:
  sss: ccc
  xxc: xxx
  project: xxx
